services:
  - type: web
    name: hysteria2-server
    runtime: image
    repo: https://github.com/maahefagilbert37-999/hysteria2-server
    plan: free
    dockerfilePath: ./Dockerfile
    ports:
      - port: 443
        protocol: udp
